version: '3'
services:
  sonarqube-lts:
    build:
      context: .
      dockerfile: src/smoke-test/sonarqube-lts
    expose:
      - 9000
    networks:
      lts:
        aliases:
          - sonarqube
  sonarqube-latest:
    build:
      context: .
      dockerfile: src/smoke-test/sonarqube-latest
    expose:
      - 9000
    networks:
      latest:
        aliases:
          - sonarqube
  test-lts:
    image: 'maven:3.6.0-jdk-8-alpine'
    volumes:
      - './src/smoke-test/smoke-test.sh:/tmp/smoke-test.sh:ro'
      - '~/.m2:/root/.m2'
    entrypoint: /tmp/smoke-test.sh
    depends_on:
      - sonarqube-lts
    networks:
      lts:
  test-latest:
    image: 'maven:3.6.0-jdk-8-alpine'
    volumes:
      - './src/smoke-test/smoke-test.sh:/tmp/smoke-test.sh:ro'
      - '~/.m2:/root/.m2'
    entrypoint: /tmp/smoke-test.sh
    depends_on:
      - sonarqube-latest
    networks:
      latest:

networks:
  lts:
  latest:
